sonar.organization=kjramos5310
sonar.projectKey=kjramos5310_ParkingApp3P
sonar.projectName=ParkingApp3P

# Fuentes de TODOS los microservicios (Java + NestJS)
sonar.sources=App/ms-usuarios-roles-auth/src/main,App/ms-zonas-espacios/src/main,App/ms-vehiculos/src,App/ms-tickets/src

# Codificación
sonar.sourceEncoding=UTF-8

# Binarios Java (necesario para que Sonar analice el bytecode compilado)
sonar.java.binaries=App/ms-usuarios-roles-auth/target/classes,App/ms-zonas-espacios/target/classes

# Exclusiones
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/*.spec.ts,**/test/**,**/*.test.ts
