spring:
  application:
    name: zonas-espacios
  datasource:
    url: jdbc:mysql://localhost:3307/db_zonas_espacios?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: espe_user
    password: espe_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082
